baseURL = 'https://sauerteig-bibel.de/'
languageCode = 'de-DE'
title = 'Sauerteig Bibel'
theme = 'hugo-book'
googleAnalytics = "G-V6WWFW2FNX"
disablePathToLower = false
enableGitInfo = true

[params]
  BookTheme = 'auto'
  BookToC = true
  BookSection = '/'
  BookLogo = 'logo.png'
  BookRepo = 'https://github.com/NodyHub/sauerteig-bibel'
  BookEditPath = 'edit/main'
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
